# 🔹 Etapa 1: Build
FROM golang:1.21 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy

COPY . .
RUN go build -o main ./cmd/main.go

# 🔹 Etapa 2: Run (Imagen final optimizada)
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 8080

CMD ["./main"]
